services:
  postgres:
    image: postgres:15-alpine
    container_name: astronum_postgres_testing
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - astronum_data_testing:/var/lib/postgresql/data
    networks:
      - astronum_network_testing

  redis:
    image: redis:7-alpine
    container_name: astronum_redis_testing
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - astronum_redis_data_testing:/data 

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: astronum_pgadmin_testing
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - astronum_network_testing

networks:
  astronum_network_testing:

volumes:
  astronum_data_testing:
  astronum_redis_data_testing:
